name: Build

on:
  release:
    types: [published]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'
        cache: true

    - name: Verify dependencies
      run: go mod verify

    - name: Create go.sum
      run: go mod tidy

    - name: Run go vet
      run: go vet ./...

    - name: Build Linux
      run: go build -ldflags "-s -w -X 'main.version=$(date +%Y%m%d)'" -v ./...

    #- name: Tar files
    #  run: tar -cvf my_files.tar /path/to/my/directory

    - uses: actions/upload-artifact@v3
      with:
        name: Archive Linux
        path: |
          csv2xlsx
          example.cfg

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -ldflags "-s -w -X 'main.version=$(date +%Y%m%d)'"  -v ./...

    - uses: actions/upload-artifact@v3
      with:
        name: Archive Windows
        path: |
          csv2xlsx.exe
