name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 'stable'
        cache: true

    - name: Verify dependencies
      run: go mod verify

    #- name: Create go.sum
    #  run: go mod tidy

    - name: Run go vet
      run: go vet ./...

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    - name: Run tests
      run: go test -race -vet=off ./...
 
 build:
   - name: Build Linux
      run: go build -ldflags "-s -w -X 'main.version=$(date +%Y%m%d)'" -v ./...

    - uses: actions/upload-artifact@v3
      with:
        name: csv2xlsx Linux
        path: |
          csv2xlsx
          example.cfg

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -ldflags "-s -w -X 'main.version=$(date +%Y%m%d)'"  -v ./...

    - uses: actions/upload-artifact@v3
      with:
        name: csv2xlsx Windows
        path: |
          csv2xlsx.exe
          example.cfg
